create table product(
    id int primary key generated by default as identity ,
    title varchar,
    description varchar,
    price int,
    type varchar,
    url_image varchar
);

create table expenditure(
    id int primary key generated by default as identity ,
    title varchar,
    weight int,
    product_id int references product(id)
);